name: ItemEdit
main: com.siamminecraft.iSuzutsuki.ItemEdit.ItemEditPlugin
version: indev
commands:
    itemedit:
        usage: /itemedit set <amount> , /itemedit add <amount>
    itemname:
        usage: /itemname <name>
    addlore:
        usage: /addlore <lore>
    clearlore:
        usage: /clearlore
    displayhand:
        usage: /displayhand (Debug cmd)
permissions:
    itemedit.unlimited:
        default: op
    itemedit.displayedit:
        default: op